### ISSUE TITLE
Want to play roblox now ggg???????????

### ISSUE THREAD

**Issue by pretzer25** [1coolmatt8083/dm-unbocker.#1]
go to ultra-learn.vercel.app

**Comment by 1coolmatt8083** [comment]
does ent work

**Comment by 1coolmatt8083** [comment]
light speed agent blockes it

**Comment by 1coolmatt8083** [comment]
it just takes me to google and then when I tyoe in roblox and go to roblox it blocked it

**Comment by 1coolmatt8083** [comment]
got any other links that work for roblox gg??

**Comment by pretzer25** [comment]
i mean you can try going to ultra-learn.vercel.app/home.html but there are no cloaks, sometimes the actual page doesn't work (ultra-learn.vercel.app) so you need to reload

**Comment by 1coolmatt8083** [comment]
ya thats just google
[Screen recording 2024-05-08 8.22.36 AM.webm](https://github.com/1coolmatt8083/dm-unbocker./assets/162379962/e9730fc3-1b6e-4396-b2fb-d54d4db1ad27)

**Comment by 1coolmatt8083** [comment]
any other links i can try??

**Comment by pretzer25** [comment]
yes try adding /home.html to the end of the url, by the way can you tell me your device so I can know whats wrong with the site?

**Comment by 1coolmatt8083** [comment]
cromebook

**Comment by 1coolmatt8083** [comment]
and i have lightspeed agent
installed by administration

**Comment by 1coolmatt8083** [comment]
does roblox now . gg work

**Comment by 1coolmatt8083** [comment]
oh wait it doesent work

**Comment by 1coolmatt8083** [comment]
it just pops up as the vpn/proxy detection

**Comment by 1coolmatt8083** [comment]
sooo do u have a solution to that

**Comment by pretzer25** [comment]
everytime you ever go on roblox on a proxy, you can you js or manually refresh the page until it doesnt say anything (1 in a 100 moments)

**Comment by 1coolmatt8083** [comment]
ya noo
